version: "1.0"
type: route
data:
  url: "/usermgmt/kerberos/settings"
  title: _("Settings")
  editing: true
  notificationTitle: _('Updated Kerberos settings.')
  component: omv-usermgmt-kerberos-form-page
