#!/bin/bash
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @author    OpenMediaVault Plugin Developers <plugins@omv-extras.org>
# @copyright Copyright (c) 2009-2013 Volker Theile
# @copyright Copyright (c) 2013-2015 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_MKCONF_SCRIPTS_DIR=${OMV_MKCONF_SCRIPTS_DIR:-"/usr/share/openmediavault/mkconf"}

OMV_KRB5_CONFIG=${OMV_KRB5_CONFIG:-"/etc/krb5.conf"}
OMV_KRB5_KEYTAB=${OMV_KRB5_KEYTAB:-"/etc/krb5.keytab"}
OMV_KRB5_EXTENSIONS_DIR=${OMV_KRB5_EXTENSIONS_DIR:-"${OMV_MKCONF_SCRIPTS_DIR}/kerberos.d"}

OMV_NFSD_V4_DEFAULT_KERBEROS_FLAGS=${OMV_NFSD_V4_DEFAULT_KERBEROS_FLAGS:-"sec=krb5p:krb5i:krb5"}
OMV_NFSD_V4_DEFAULT_EXPORT_OPTIONS=${OMV_NFSD_V4_DEFAULT_EXPORT_OPTIONS:-""}

rm -f ${OMV_KRB5_CONFIG}

if [[ "$(omv_config_get "//services/kerberos/enable")" = "1" &&
	  "$(omv_config_get "//services/nfs/enable")" = "1" &&
	  "$(omv_config_get "//services/kerberos/nfs-enabled")" = "1" ]]; then
	OMV_NFSD_NEEDSVCGSSD="yes"
else
	OMV_NFSD_NEEDSVCGSSD=""
fi

omv_set_default "OMV_NFSD_NEEDSVCGSSD" "${OMV_NFSD_NEEDSVCGSSD}"
omv_set_default "OMV_NFSD_V4_DEFAULT_EXPORT_OPTIONS" $(echo ${OMV_NFSD_V4_DEFAULT_EXPORT_OPTIONS} | sed 's/'",*${OMV_NFSD_V4_DEFAULT_KERBEROS_FLAGS}"'//g')

run-parts --exit-on-error ${OMV_KRB5_EXTENSIONS_DIR}